# Site settings
port: 4000
title: webtwic
email: info@webtwic.com
description: A community for coding and tech tweaks where beginners and experts can learn.
# baseurl: "http://webtwic.com"
# url: "http://webtwic.com" # the base hostname & protocol for your site
twitter_username: webtwic
github_username:  webtwic
facebook_name: webtwic
google_name: webtwic

# Build settings
markdown: kramdown
